//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.KETOAN.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.KETOAN.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete batch employee failed..
        /// </summary>
        public static string DeleteBatchEmployeeError_DevMsg {
            get {
                return ResourceManager.GetString("DeleteBatchEmployeeError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhiều nhân viên thất bại..
        /// </summary>
        public static string DeleteBatchEmployeeError_UserMsg {
            get {
                return ResourceManager.GetString("DeleteBatchEmployeeError_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record failed..
        /// </summary>
        public static string DeleteError_DevMsg {
            get {
                return ResourceManager.GetString("DeleteError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thất bại..
        /// </summary>
        public static string DeleteError_UserMsg {
            get {
                return ResourceManager.GetString("DeleteError_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra ngoại lệ..
        /// </summary>
        public static string Exception_DevMsg {
            get {
                return ResourceManager.GetString("Exception_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ Misa để được hỗ trợ..
        /// </summary>
        public static string Exception_UserMsg {
            get {
                return ResourceManager.GetString("Exception_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get record from database failed..
        /// </summary>
        public static string GetDataError_DevMsg {
            get {
                return ResourceManager.GetString("GetDataError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy bản ghi thất bại..
        /// </summary>
        public static string GetDataError_UserMsg {
            get {
                return ResourceManager.GetString("GetDataError_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new employee code failed..
        /// </summary>
        public static string GetNewEmployeeCodeError_DevMsg {
            get {
                return ResourceManager.GetString("GetNewEmployeeCodeError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã nhân viên mới thất bại..
        /// </summary>
        public static string GetNewEmployeeCodeError_UserMsg {
            get {
                return ResourceManager.GetString("GetNewEmployeeCodeError_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert record failed..
        /// </summary>
        public static string InsertError_DevMsg {
            get {
                return ResourceManager.GetString("InsertError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bản ghi thất bại..
        /// </summary>
        public static string InsertError_UserMsg {
            get {
                return ResourceManager.GetString("InsertError_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://open.api/error-code/.
        /// </summary>
        public static string MoreInfoMsg {
            get {
                return ResourceManager.GetString("MoreInfoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update record failed..
        /// </summary>
        public static string UpdateError_DevMsg {
            get {
                return ResourceManager.GetString("UpdateError_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bản ghi thất bại..
        /// </summary>
        public static string UpdateError_UserMsg {
            get {
                return ResourceManager.GetString("UpdateError_UserMsg", resourceCulture);
            }
        }
    }
}
